import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { analytics } from '../firebase'
import { useEffect,useState } from 'react'
import { getAnalytics, logEvent } from "firebase/analytics"
import Layout from '../components/layout'
import { useAuth } from '../context'
import {useSelector,useDispatch} from 'react-redux'
import {setProducts,setName} from '../store/global'
export default function Home({}) {

//const [products, setProducts] = useState([])
const {ProductsBY,products} = useAuth()
const {} = useSelector(state=>state.global)
const dispatch = useDispatch()
useEffect(() => {
const analytics = getAnalytics();
logEvent(analytics, "screen_view", {
  firebase_screen: "Home",
});
}, []);


useEffect(() => {

ProductsBY('createdAt')




}, [])






  return (
    <div  className='mt-4'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


<Layout
    title="FullStack React Node MongoDB Ecommerce App"
    description="Node React E-commerce App"

>

<div>
 {products?.length}
</div>


</Layout>


     
    </div>
  )
}
